text = '[["accounts.google.com/signup/v2/webcreateaccount","franckmiranda2008","17851706"],["accounts.google.com/o/oauth2/v2/auth/identifier","kaleb.carvajal.rayon@gmail.com","Partner#1981"],["accounts.google.com/signin/v2/sl/pwd","taibarbia@gmail.com","21061964ra"],["accounts.google.com/signup/v2/webcreateaccount","michealwaweru0014","Sami10014"],["accounts.google.com/signin/v2/challenge/pwd","gatminmiggy@gmail.com","miggy0595"],["accounts.google.com/signin/v2/sl/pwd","marvelfact52@gmail.com","Burungku11"],["accounts.google.com/signin/v2/challenge/pwd","pitogaro@gmail.com","fxxkevo599"],["accounts.google.com/signin/challenge/sl/password","rikiyakub2002@gmail.com","rikiyakub0409"],["accounts.google.com/signin/v2/challenge/pwd","popeddlj@gmail.com","panni123***"],["myaccount.google.com/u/3/signinoptions/password","b-27264@student.usa.edu.pk","Usa@rasim99"],["accounts.google.com/signin/v2/challenge/pwd","grantajoryan1@gmail.com","oneforrestone__"],["accounts.google.com/SignUp","vannguyen10720","vancute77"],["accounts.google.com/signin/v2/challenge/pwd","rosemyrlandegeorges22@gmail.com","Myrlande22"],["accounts.google.com/","rbjd961920@gmail.com","vijayjadhav1965#"],["accounts.google.com/signin/challenge/sl/password","anwar.resalakfs2090@gmail.com","sararedaahmedshamakh20902090"],["accounts.google.com/signin/v2/challenge/pwd","pavalamalar0402@gmail.com","rabishan04G."],["accounts.google.com/v3/signin/challenge/pwd","ayazemir190319@gmail.com","papatya1903"],["accounts.google.com/signin/v2/sl/pwd","flipflopsnloafers@gmail.com","ffnlofficial@273#"],["accounts.google.com/signin/v2/challenge/pwd","princeatiqk@gmail.com","524524123"],["accounts.google.com/ServiceLoginAuth","csehtunde21@gmail.com","eszdavi21"],["accounts.google.com/","muqtadir15-11661@diu.edu.bd","94326zidan"],["accounts.google.com/signin/v2/challenge/pwd","xxikniw@gmail.com","gilnwe11412"],["accounts.google.com","reamhoer555@gmail.com","klipang123"],["accounts.google.com/AddSession","kacper.murdza36@gmail.com","repcak326"],["accounts.google.com/signin/v2/identifier","sergejsavic123123@gmail.com","kalemrale123"],["accounts.google.com/SignUp","achaouchi02@gmail.com","Amina1979."],["accounts.google.com/v3/signin/challenge/pwd","nithyamtvchennai@gmail.com","Nithyam$$2022"],["myaccount.google.com/","chaymaebouazgou@gmail.com","omar10101010"],["accounts.google.com/signin/v2/challenge/pwd","nadjavujasin06","jovana07072007"],["accounts.google.com/signin/v2/challenge/pwd","juniorstarchhieronymos@gmail.com","HJs@2077"],["accounts.google.com/SignUp","FerryWah77","082148789003"],["accounts.google.com/signin/v2/sl/pwd","nguyenanhngohan@gmail.com","NULL"],["accounts.google.com/SignUp","nistorbriana23","fabiotiamo"],["accounts.google.com/signin/v2/challenge/pwd","legionscollection@gmail.com","LegionsCollection123"],["accounts.google.com/ServiceLogin/identifier","kaloqn81dimitrov","alo05alo14*"],["accounts.google.com/AddSession","enio.projetos","Ufes25121987"]]'



content = text.replace("[", "").replace("]", "")
elements = content.split(",")

result = []
for i in range(0, len(elements), 3):
    sublist = []
    for element in elements[i:i+3]:
        element = element[1: -1]
        sublist.append(element)
    
    result.append(sublist)

print(result[10][1])